import type { ReportTemplate } from '../types';

export const mockTemplates: ReportTemplate[] = [
  // 系统模板
  {
    id: 'RPT-TPL-SYS-001',
    name: '经营日报',
    description: '按日生成的经营汇总报表，包含各站点营收、订单和充装量数据',
    dataSource: 'operations',
    dimensions: ['time', 'station'],
    metrics: ['revenue', 'orders', 'fuelVolume', 'avgOrderValue'],
    timeGranularity: 'day',
    defaultFilters: { defaultPeriodDays: 1 },
    tag: 'daily',
    isSystem: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'RPT-TPL-SYS-002',
    name: '经营月报',
    description: '按月生成的经营汇总报表，含站点排名和燃料占比分析',
    dataSource: 'operations',
    dimensions: ['time', 'station', 'fuelType'],
    metrics: ['revenue', 'orders', 'fuelVolume', 'avgOrderValue'],
    timeGranularity: 'month',
    defaultFilters: { defaultPeriodDays: 30 },
    tag: 'monthly',
    isSystem: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'RPT-TPL-SYS-003',
    name: '交接班报表',
    description: '按班次汇总交接班营收和支付方式分布',
    dataSource: 'operations',
    dimensions: ['shift', 'station'],
    metrics: ['revenue', 'orders', 'fuelVolume'],
    timeGranularity: 'day',
    defaultFilters: { defaultPeriodDays: 1 },
    tag: 'daily',
    isSystem: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'RPT-TPL-SYS-004',
    name: '巡检报表',
    description: '按周/月汇总巡检执行率、问题发现和整改情况',
    dataSource: 'inspection',
    dimensions: ['time', 'station'],
    metrics: ['inspectionCompletionRate', 'issueCount', 'rectificationRate'],
    timeGranularity: 'week',
    defaultFilters: { defaultPeriodDays: 7 },
    tag: 'daily',
    isSystem: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'RPT-TPL-SYS-005',
    name: '库存报表',
    description: '按日/周汇总各站点各燃料类型的入库、出库和损耗数据',
    dataSource: 'inventory',
    dimensions: ['time', 'station', 'fuelType'],
    metrics: ['inboundVolume', 'outboundVolume', 'lossVolume', 'tankLevelRatio'],
    timeGranularity: 'day',
    defaultFilters: { defaultPeriodDays: 7 },
    tag: 'daily',
    isSystem: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  // 自定义模板
  {
    id: 'RPT-TPL-0001',
    name: '月度站点对比',
    description: '按月对比各站点经营指标',
    dataSource: 'operations',
    dimensions: ['station', 'time'],
    metrics: ['revenue', 'orders', 'fuelVolume'],
    timeGranularity: 'month',
    defaultFilters: { defaultPeriodDays: 30 },
    tag: 'monthly',
    isSystem: false,
    createdBy: 'U001',
    createdAt: '2026-02-15T10:30:00Z',
    updatedAt: '2026-03-01T14:20:00Z',
  },
  {
    id: 'RPT-TPL-0002',
    name: '周度库存损耗分析',
    description: '按周统计各站点损耗率，识别异常损耗',
    dataSource: 'inventory',
    dimensions: ['time', 'station'],
    metrics: ['lossVolume', 'outboundVolume', 'tankLevelRatio'],
    timeGranularity: 'week',
    defaultFilters: { defaultPeriodDays: 7 },
    tag: 'special',
    isSystem: false,
    createdBy: 'U001',
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-02-20T09:00:00Z',
  },
  {
    id: 'RPT-TPL-0003',
    name: '巡检整改追踪',
    description: '按月追踪巡检整改完成率',
    dataSource: 'inspection',
    dimensions: ['time'],
    metrics: ['issueCount', 'rectificationRate'],
    timeGranularity: 'month',
    defaultFilters: { defaultPeriodDays: 30 },
    tag: 'monthly',
    isSystem: false,
    createdBy: 'U001',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },
];
