// 中文翻译
export default {
  // 通用
  common: {
    save: '保存',
    cancel: '取消',
    confirm: '确认',
    delete: '删除',
    edit: '编辑',
    add: '新增',
    search: '搜索',
    reset: '重置',
    actions: '操作',
    status: '状态',
    loading: '加载中...',
    noData: '暂无数据',
    success: '操作成功',
    error: '操作失败',
    required: '必填',
    optional: '选填',
    all: '全部',
    enabled: '启用',
    disabled: '停用',
    yes: '是',
    no: '否',
    back: '返回',
    detail: '详情',
    export: '导出',
    import: '导入',
    pageNotFound: '抱歉，您访问的页面不存在',
    backToHome: '返回首页',
    resetFilters: '重置筛选',
    stationUpdateSuccess: '站点更新成功',
    stationCreateSuccess: '站点创建成功',
    submitFailed: '提交失败，请检查表单',
    stationDisabled: '站点已停用',
    viewSwitch: '视图切换',
    tableView: '表格视图',
    cardView: '卡片视图',
  },

  // 导航菜单
  menu: {
    operations: '基础运营',
    station: '站点管理',
    shift: '交接班',
    equipment: '设备管理',
    inspection: '巡检管理',
  },

  // 站点管理模块
  station: {
    title: '站点管理',
    list: '站点列表',
    detail: '站点详情',
    add: '新增站点',
    edit: '编辑站点',
    
    // 字段
    name: '站点名称',
    code: '站点编码',
    address: '地址',
    longitude: '经度',
    latitude: '纬度',
    contact: '联系人',
    phone: '联系电话',
    businessHours: '营业时间',
    regionLabel: '所属区域',
    groupLabel: '所属分组',
    status: '站点状态',
    
    // 状态
    statusActive: '运营中',
    statusInactive: '已停用',
    statusMaintenance: '维护中',
    
    // 操作
    switchStation: '切换站点',
    selectStation: '请选择站点',
    
    // Tabs
    tabBasic: '基本信息',
    tabNozzle: '枪配置',
    tabShift: '班次排班',
    tabPhoto: '站点照片',
    tabEmployee: '员工管理',
    
    // 枪配置
    nozzle: {
      title: '枪配置',
      list: '枪列表',
      add: '新增枪',
      edit: '编辑枪',
      code: '枪号',
      fuelType: '燃料类型',
      unitPrice: '单价',
      status: '状态',
      setPrice: '设置单价',
      enable: '启用',
      disable: '停用',
      statusOnline: '在线',
      statusOffline: '离线',
      statusFueling: '充装中',
      statusFault: '故障',
      statusIdle: '空闲',
      businessStatus: '业务状态',
      dispenser: '加注岛',
    },
    
    // 设备状态
    device: {
      online: '在线',
      offline: '离线',
      error: '故障',
    },
    
    // 员工
    employee: {
      no: '工号',
      name: '姓名',
      phone: '电话',
      position: '岗位',
      source: '来源',
      sourceSync: '系统同步',
      sourceLocal: '本地维护',
      syncModeSync: '从用户模块同步',
      syncModeLocal: '本地独立维护',
      list: '员工列表',
    },
    
    // 表单
    form: {
      basicInfo: '基础信息',
      locationInfo: '位置信息',
      contactAndBusiness: '联系与营业',
      confirmSubmit: '确认提交',
      stationCodeDesc: '站点名称与编码',
      addressAndRegion: '地址与区域',
      contactAndHours: '联系方式与营业时间',
      infoPreview: '信息预览',
      codeModeAuto: '自动生成',
      codeModeManual: '手工输入',
      autoGenerated: '自动生成',
      weekdayHours: '工作日营业时间',
      weekendHours: '周末营业时间',
      employeeSyncMode: '员工管理模式',
      confirmInfo: '确认信息',
      coordinate: '坐标',
      confirmLeave: '确定要离开吗？未保存的数据将丢失',
      nextStep: '下一步',
    },
    
    // 详情页
    detailPage: {
      stationInfo: '站点信息',
      overview: '统计概览',
      overnight: '跨天',
      nozzleConfig: '枪配置列表',
      refreshStatus: '刷新状态',
      viewNozzleConfig: '查看枪配置',
      errorNozzleAlert: '该站点有 {{count}} 台枪处于故障状态',
      confirmDisableStation: '确定要停用该站点吗？',
      noPhoto: '暂无照片',
    },
  },

  // 燃料类型
  fuelType: {
    gasoline92: '92#汽油',
    gasoline95: '95#汽油',
    gasoline98: '98#汽油',
    diesel: '柴油',
    cng: 'CNG',
    lng: 'LNG',
    other: '其他',
  },
};
