// 中文翻译
export default {
  // 应用
  app: {
    title: '加气站管理系统',
  },

  // 通用
  common: {
    save: '保存',
    cancel: '取消',
    confirm: '确认',
    delete: '删除',
    edit: '编辑',
    add: '新增',
    search: '搜索',
    reset: '重置',
    actions: '操作',
    status: '状态',
    loading: '加载中...',
    noData: '暂无数据',
    success: '操作成功',
    error: '操作失败',
    required: '必填',
    optional: '选填',
    all: '全部',
    enabled: '启用',
    disabled: '停用',
    yes: '是',
    no: '否',
    back: '返回',
    detail: '详情',
    export: '导出',
    import: '导入',
    pageNotFound: '抱歉，您访问的页面不存在',
    backToHome: '返回首页',
    resetFilters: '重置筛选',
    stationUpdateSuccess: '站点更新成功',
    stationCreateSuccess: '站点创建成功',
    submitFailed: '提交失败，请检查表单',
    stationDisabled: '站点已停用',
    viewSwitch: '视图切换',
    tableView: '表格视图',
    cardView: '卡片视图',
    prevStep: '上一步',
    nextStep: '下一步',
    totalRecords: '共 {{total}} 条记录',
    refresh: '刷新',
    autoRefresh: '自动刷新',
    view: '查看',
    total: '共',
    records: '条',
    comingSoon: '功能即将上线',
    exportTodo: '导出功能即将上线',
  },

  // 导航菜单
  menu: {
    operations: '基础运营',
    station: '站点管理',
    shift: '交接班',
    shiftOverview: '站点概况',
    shiftSchedule: '排班表',
    shiftHistory: '交接历史',
    shiftSettlementReview: '解缴审核',
    equipment: '设备管理',
    inspection: '巡检/安检管理',
    inspectionTasks: '安检任务',
    inspectionPlans: '安检计划',
    inspectionCheckItems: '检查项目',
    inspectionIssues: '问题记录',
    inspectionLogs: '巡检日志',
    inspectionAnalytics: '统计报表',
    deviceLedger: '设备设施',
    facilityMonitoring: '设施监控',
    equipmentLedger: '设备台账',
    maintenanceOrders: '维保工单',
    deviceConnectivity: '设备连接',
    energyTrade: '能源交易',
    priceManagement: '价格管理',
    priceOverview: '价格总览',
    priceHistory: '调价历史',
    priceBoard: '价格公示',
    priceApproval: '调价审批',
    memberPrices: '会员专享价',
    priceAgreements: '价格协议',
    priceSettings: '价格设置',
    orderTransaction: '订单交易',
    orderList: '订单列表',
    orderExceptions: '异常订单',
    orderRefunds: '退款管理',
    orderSettings: '订单设置',
  },

  // 用户身份
  user: {
    signOut: '退出登录',
    signOutConfirm: '确定要退出登录吗？',
    signedOut: '已退出登录',
    role: {
      station_master: '站长',
      shift_leader: '班长',
      cashier: '收银员',
      finance: '财务',
    },
  },

  // 站点管理模块
  station: {
    title: '站点管理',
    list: '站点列表',
    detail: '站点详情',
    add: '新增站点',
    edit: '编辑站点',
    
    // 字段
    name: '站点名称',
    code: '站点编码',
    address: '地址',
    longitude: '经度',
    latitude: '纬度',
    contact: '联系人',
    phone: '联系电话',
    businessHours: '营业时间',
    regionLabel: '所属区域',
    groupLabel: '所属分组',
    status: '站点状态',
    
    // 状态
    statusActive: '运营中',
    statusInactive: '已停用',
    statusMaintenance: '维护中',
    
    // 操作
    switchStation: '切换站点',
    selectStation: '请选择站点',
    
    // Tabs
    tabBasic: '基本信息',
    tabNozzle: '枪配置',
    tabShift: '班次排班',
    tabPhoto: '站点照片',
    tabEmployee: '员工管理',
    
    // 枪配置
    nozzle: {
      title: '枪配置',
      list: '枪列表',
      add: '新增枪',
      edit: '编辑枪',
      code: '枪号',
      fuelType: '燃料类型',
      unitPrice: '单价',
      status: '状态',
      setPrice: '设置单价',
      enable: '启用',
      disable: '停用',
      statusOnline: '在线',
      statusOffline: '离线',
      statusFueling: '充装中',
      statusFault: '故障',
      statusIdle: '空闲',
      businessStatus: '业务状态',
      dispenser: '加注岛',
    },
    
    // 设备状态
    device: {
      online: '在线',
      offline: '离线',
      error: '故障',
    },
    
    // 员工
    employee: {
      no: '工号',
      name: '姓名',
      phone: '电话',
      position: '岗位',
      source: '来源',
      sourceSync: '系统同步',
      sourceLocal: '本地维护',
      syncModeSync: '从用户模块同步',
      syncModeLocal: '本地独立维护',
      list: '员工列表',
    },
    
    // 表单
    form: {
      basicInfo: '基础信息',
      locationInfo: '位置信息',
      contactAndBusiness: '联系与营业',
      confirmSubmit: '确认提交',
      stationCodeDesc: '站点名称与编码',
      addressAndRegion: '地址与区域',
      contactAndHours: '联系方式与营业时间',
      infoPreview: '信息预览',
      codeModeAuto: '自动生成',
      codeModeManual: '手工输入',
      autoGenerated: '自动生成',
      weekdayHours: '工作日营业时间',
      weekendHours: '周末营业时间',
      employeeSyncMode: '员工管理模式',
      confirmInfo: '确认信息',
      coordinate: '坐标',
      confirmLeave: '确定要离开吗？未保存的数据将丢失',
      nextStep: '下一步',
    },
    
    // 班次定义
    shift: {
      title: '班次',
      name: '班次名称',
      list: '班次列表',
      add: '新增班次',
      startTime: '开始时间',
      endTime: '结束时间',
      supervisor: '负责人',
      definitionsTab: '班次定义',
      scheduleTab: '排班日历',
    },

    // 排班日历（周视图）
    schedule: {
      title: '排班表',
      shift: '班次',
      date: '日期',
      employee: '值班人员',
      addSchedule: '新增排班',
      editSchedule: '编辑排班',
      saveSuccess: '排班保存成功',
      thisWeek: '本周',
      prevWeek: '上一周',
      nextWeek: '下一周',
    },

    // 站点照片
    photo: {
      title: '站点照片',
      upload: '上传照片',
    },

    // 详情页
    detailPage: {
      stationInfo: '站点信息',
      overview: '统计概览',
      overnight: '跨天',
      nozzleConfig: '枪配置列表',
      refreshStatus: '刷新状态',
      viewNozzleConfig: '查看枪配置',
      errorNozzleAlert: '该站点有 {{count}} 台枪处于故障状态',
      confirmDisableStation: '确定要停用该站点吗？',
      noPhoto: '暂无照片',
    },
  },

  // 燃料类型
  fuelType: {
    gasoline92: '92#汽油',
    gasoline95: '95#汽油',
    gasoline98: '98#汽油',
    diesel: '柴油',
    cng: 'CNG',
    lng: 'LNG',
    other: '其他',
  },

  // 交接班管理模块
  shiftHandover: {
    // 页面标题
    title: '交接班管理',
    summaryTitle: '当班概况',
    historyTitle: '交接历史',
    detailTitle: '交接详情',
    wizardTitle: '交接班流程',
    wizardSubtitle: '请按步骤完成交接班操作',
    settlementReviewTitle: '解缴审核',
    
    // 当班概况
    currentShift: '当前班次',
    shiftTime: '班次时间',
    shiftDuration: '已运营',
    hoursUnit: '小时',
    startHandover: '发起交接',
    viewHistory: '查看历史',
    cashSettlement: '现金解缴',
    settlementReview: '解缴审核',
    
    // 统计数据
    totalAmount: '销售总额',
    totalOrders: '总订单数',
    ordersUnit: '笔',
    netAmount: '净收入',
    abnormalCount: '异常笔数',
    refundCount: '退款笔数',
    refundAmount: '退款金额',
    fuelQuantity: '充装量',
    comparedToPrevious: '较上班次',
    dataRefreshed: '数据已更新',
    refreshFailed: '数据刷新失败，请重试',
    lastUpdated: '最后更新',
    seconds: '秒',
    unsettledCash: '现金待解缴',
    autoRefreshInterval: '自动刷新间隔',
    
    // 金额显示
    hideAmount: '隐藏金额',
    showAmount: '显示金额',
    amountHidden: '****',
    
    // 支付方式
    byPaymentMethod: '按支付方式',
    paymentMethod: '支付方式',
    cash: '现金',
    wechat: '微信支付',
    alipay: '支付宝',
    unionpay: '银联卡',
    prepaid: '预付卡',
    credit: '挂账',
    other: '其他',
    
    // 燃料类型
    byFuelType: '按燃料类型',
    fuelType: '燃料类型',
    quantity: '数量',
    amount: '金额',
    orders: '订单数',
    
    // 交接历史
    dateRange: '日期范围',
    station: '站点',
    shiftName: '班次',
    stationName: '站点名称',
    shiftDate: '班次日期',
    handoverTime: '交接时间',
    handoverBy: '交接人',
    receivedBy: '接班人',
    recordsUnit: '条',
    viewDetail: '查看详情',
    
    // 状态
    initiated: '已发起',
    pendingReview: '待审核',
    completed: '已完成',
    cancelled: '已取消',
    approved: '已通过',
    rejected: '已驳回',
    
    // 详情页
    recordNotFound: '未找到交接记录',
    basicInfo: '基本信息',
    handoverNo: '交接单号',
    salesSummary: '销售汇总',
    issueRecords: '异常记录',
    noIssues: '无异常记录',
    forcedHandover: '强制交接',
    print: '打印',
    remarks: '交接备注',
    
    // 异常
    issueType: '异常类型',
    severity: '严重程度',
    description: '描述',
    reportedBy: '上报人',
    resolved: '已解决',
    unresolved: '未解决',
    
    // 现金解缴
    expectedAmount: '应缴金额',
    actualAmount: '实缴金额',
    difference: '差额',
    differenceReason: '差额原因',
    differenceNote: '差额说明',
    settlementMethod: '解缴方式',
    settlementNo: '解缴单号',
    settlementTime: '解缴时间',
    settlementStatus: '解缴状态',
    submittedBy: '提交人',
    reviewedBy: '审核人',
    reviewedAt: '审核时间',
    
    // 差额类型
    balanced: '无差额',
    overage: '长款 ¥{{amount}}',
    shortage: '短款 ¥{{amount}}',
    
    // 解缴方式
    methodCashBox: '投入钱箱',
    methodSafe: '存入保险柜',
    methodBank: '银行存款',
    
    // 向导步骤
    stepPrecheck: '交接预检',
    stepSummary: '销售汇总',
    stepSettlement: '现金解缴',
    stepConfirm: '确认提交',
    
    // 预检
    precheckTip: '请确认以下事项已完成，带 * 的为必选项',
    checkAll: '全部勾选',
    completeRequiredItems: '请完成所有必选项',
    
    // 解缴
    settlementTip: '请核对并输入实际缴纳的现金金额',
    enterActualAmount: '请输入实缴金额',
    enterDifferenceReason: '差额超过10元，请填写原因',
    differenceReasonPlaceholder: '请说明差额产生的原因',
    
    // 确认
    confirmTip: '请确认以下交接信息无误后提交',
    shiftInfo: '班次信息',
    remarksPlaceholder: '如有需要交接的事项，请在此备注',
    
    // 提交
    confirmSubmit: '确认提交',
    submitSuccess: '交接班提交成功',
    submitFailed: '提交失败，请重试',
    cancelHandover: '取消交接',
    confirmCancel: '确定取消交接吗？',
    cancelWarning: '取消后已填写的数据将丢失',
    
    // 强制交接
    forceHandover: '强制交接',
    forceHandoverTitle: '强制交接确认',
    forceHandoverWarning: '预检项目未全部完成，确定要强制提交交接吗？此操作将被记录。',
    confirmForce: '确认强制提交',
    
    // 完成
    handoverSuccess: '交接班已完成',
    handoverSuccessTip: '交接信息已提交，等待接班人确认',
    backToSummary: '返回当班概况',
    
    // 审核
    review: '审核',
    reviewSettlement: '审核解缴',
    reviewResult: '审核结果',
    approve: '通过',
    reject: '驳回',
    reviewNote: '审核备注',
    reviewNotePlaceholder: '可选填审核备注',
    enterRejectReason: '请填写驳回原因',
    rejectReasonPlaceholder: '请说明驳回原因',
    submitReview: '提交审核',
    reviewApproveSuccess: '审核通过',
    reviewRejectSuccess: '审核已驳回',
    
    // 统计
    pendingReviewCount: '待审核',
    totalDifferenceSum: '差额合计',

    // 接班人选择
    selectReceiver: '选择接班人',
    selectReceiverPlaceholder: '请选择接班人',
    receiverHint: '仅显示当前站点排班表中的人员。如未找到对应人员，请前往「站点管理 → 员工管理」确认该员工已添加至排班表。',
    receiverRequired: '请选择接班人',

    // 排班表
    scheduleTitle: '排班表',
    scheduleThisWeek: '本周',
    scheduleThisMonth: '本月',
    schedulePrevWeek: '上一周',
    scheduleNextWeek: '下一周',
    scheduleAddShift: '新增排班',
    scheduleEditShift: '编辑排班',
    scheduleDate: '日期',
    scheduleShift: '班次',
    scheduleEmployee: '值班人员',
    scheduleSave: '保存',
    scheduleSaveSuccess: '排班保存成功',
    scheduleNoData: '暂无排班数据，请先创建排班',
    scheduleGoToSchedule: '前往创建排班',

    // 站点概况
    overviewTitle: '站点概况',
    currentShiftInfo: '当前班次',
    nextShiftInfo: '下一班次',
    selectStation: '请选择站点',
    switchStation: '切换站点',
    noScheduleHint: '暂无排班信息，请先创建排班',
    scheduled: '已排班',
  },

  // 设备设施管理模块
  deviceLedger: {
    // 设施监控
    monitoring: {
      title: '设施监控',
      totalDevices: '设备总数',
      onlineRate: '在线率',
      alarms: '告警数',
      pendingMaintenance: '待维保',
      tankSection: '储罐状态',
      dispenserSection: '加气机状态',
      pendingActions: '待处理事项',
      autoRefresh: '自动刷新中',
      tankDetail: '储罐监控',
      dispenserDetail: '加气机状态板',
      level: '液位',
      pressure: '压力',
      temperature: '温度',
      trend: '趋势图',
    },
    // 设备台账
    equipment: {
      title: '设备台账',
      add: '新增设备',
      edit: '编辑设备',
      create: '新增设备',
      detail: '设备详情',
      deviceCode: '设备编号',
      name: '名称',
      type: '类型',
      model: '型号',
      status: '状态',
      installDate: '安装日期',
      nextMaintenance: '下次维保',
    },
    // 维保工单
    maintenance: {
      title: '维保工单',
      report: '故障报修',
      createOrder: '创建维保工单',
      submit: '提交工单',
      orderNumber: '工单号',
      type: '类型',
      device: '关联设备',
      urgency: '紧急程度',
      status: '状态',
      assignee: '处理人',
      createdAt: '创建时间',
      description: '描述',
    },
    // 设备连接
    connectivity: {
      title: '设备连接',
    },
  },

  // 巡检/安检管理模块
  inspection: {
    // 页面标题
    title: '巡检/安检管理',
    taskTitle: '安检任务',
    planTitle: '安检计划',
    checkItemTitle: '检查项目',
    issueTitle: '问题记录',
    logTitle: '巡检日志',
    analyticsTitle: '统计报表',

    // 计划状态
    planStatus: {
      pending: '待执行',
      active: '执行中',
      completed: '已完成',
      cancelled: '已取消',
    },

    // 任务状态
    taskStatus: {
      pending: '待执行',
      inProgress: '执行中',
      completed: '已完成',
      overdue: '已逾期',
      cancelled: '已取消',
    },

    // 检查结果
    checkResult: {
      normal: '正常',
      abnormal: '异常',
      skipped: '跳过',
      notChecked: '未检查',
    },

    // 问题严重程度
    severity: {
      critical: '严重',
      major: '重要',
      minor: '一般',
      suggestion: '建议',
    },

    // 问题状态
    issueStatus: {
      pending: '待处理',
      processing: '处理中',
      pendingReview: '待审核',
      resolved: '已解决',
      closed: '已关闭',
    },

    // 检查周期
    cycleType: {
      daily: '每日',
      weekly: '每周',
      monthly: '每月',
      quarterly: '每季度',
      custom: '自定义',
    },

    // 检查项分类
    category: {
      safety_equipment: '安全设备',
      fire_protection: '消防设施',
      electrical: '电气设施',
      pressure_vessel: '压力容器',
      environmental: '环保设施',
      general_facility: '通用设施',
    },

    // 任务列表
    task: {
      totalTasks: '总任务数',
      pendingTasks: '待执行',
      overdueTasks: '已逾期',
      todayCompleted: '今日完成',
      pendingIssues: '待处理问题',
      taskNo: '任务编号',
      planName: '关联计划',
      assignee: '执行人',
      scheduledTime: '计划时间',
      deadlineTime: '截止时间',
      completedAt: '完成时间',
      progress: '进度',
      assign: '指派',
      assignTo: '指派给',
      selectAssignee: '请选择执行人',
      assignSuccess: '指派成功',
      noTasks: '暂无安检任务',
      noTasksHint: '请先创建安检计划并生成任务',
      goToPlans: '前往创建计划',
      overdue: '已逾期',
      dueSoon: '即将到期',
    },

    // 任务执行
    execution: {
      backToList: '返回列表',
      taskInfo: '任务信息',
      allNormal: '全部正常',
      allNormalConfirm: '确认将所有未检查项标记为正常？',
      submitTask: '提交任务',
      submitConfirm: '确认提交？未检查的项目将标记为跳过。',
      submitSuccess: '任务提交成功',
      saveProgress: '保存进度',
      saveSuccess: '进度已保存',
      checkedCount: '已检查 {{checked}}/{{total}}',
      normalCount: '正常',
      abnormalCount: '异常',
      remark: '备注',
      remarkPlaceholder: '请输入异常说明',
      guideTip: '点击「正常」或「异常」按钮记录检查结果',
    },

    // 计划列表
    plan: {
      createPlan: '新建计划',
      planNo: '计划编号',
      name: '计划名称',
      cycle: '执行周期',
      station: '适用站点',
      checkItemCount: '检查项数量',
      estimatedTasks: '预计任务数',
      createdBy: '创建人',
      createdAt: '创建时间',
      startDate: '开始日期',
      endDate: '结束日期',
      editPlan: '编辑计划',
      cancelPlan: '取消计划',
      cancelConfirm: '确定取消该计划？取消后不再生成新任务。',
      cancelSuccess: '计划已取消',
      dispatch: '派发任务',
      dispatchSuccess: '任务派发成功',
      noPlan: '暂无安检计划',
      noPlanHint: '点击右上角按钮创建您的第一个安检计划',
    },

    // 计划表单
    planForm: {
      create: '新建安检计划',
      edit: '编辑安检计划',
      basicInfo: '基本信息',
      selectCheckItems: '选择检查项',
      namePlaceholder: '请输入计划名称',
      stationPlaceholder: '请选择适用站点',
      cyclePlaceholder: '请选择执行周期',
      selectedItems: '已选检查项',
      availableItems: '可选检查项',
      noItemsSelected: '请至少选择一个检查项',
      saveSuccess: '计划保存成功',
      confirmLeave: '确定要离开吗？未保存的数据将丢失',
    },

    // 计划详情
    planDetail: {
      backToList: '返回列表',
      planInfo: '计划信息',
      associatedTasks: '关联任务',
      noTasks: '暂无关联任务',
      viewTask: '查看任务',
    },

    // 检查项目
    checkItem: {
      addItem: '新增检查项',
      editItem: '编辑检查项',
      manageTags: '管理标签',
      name: '项目名称',
      category: '分类',
      description: '检查标准',
      station: '适用站点',
      equipment: '关联设备',
      tags: '标签',
      status: '状态',
      active: '启用',
      inactive: '停用',
      deactivate: '停用',
      activate: '启用',
      deactivateConfirm: '确定停用该检查项？停用后计划中将跳过此项。',
      activateConfirm: '确定启用该检查项？',
      deactivateSuccess: '检查项已停用',
      activateSuccess: '检查项已启用',
      noItems: '暂无检查项目',
      noItemsHint: '点击右上角按钮添加您的第一个检查项',
      namePlaceholder: '请输入检查项名称',
      descriptionPlaceholder: '请输入检查标准或描述',
      categoryPlaceholder: '请选择分类',
      stationPlaceholder: '请选择适用站点',
      equipmentPlaceholder: '请选择关联设备',
      tagPlaceholder: '请选择标签',
      saveSuccess: '检查项保存成功',
    },

    // 标签管理
    tag: {
      title: '标签管理',
      name: '标签名称',
      color: '标签颜色',
      addTag: '新增标签',
      editTag: '编辑标签',
      deleteTag: '删除标签',
      deleteConfirm: '确定删除该标签？',
      deleteSuccess: '标签已删除',
      saveSuccess: '标签已保存',
      namePlaceholder: '请输入标签名称',
    },

    // 问题记录
    issue: {
      reportIssue: '上报问题',
      issueNo: '问题编号',
      title: '问题标题',
      severity: '严重程度',
      status: '处理状态',
      source: '来源',
      fromInspection: '巡检发现',
      fromManual: '手动上报',
      reportedBy: '上报人',
      reportedAt: '上报时间',
      assignedTo: '处理人',
      dueDate: '处理期限',
      resolvedAt: '解决时间',
      description: '问题描述',
      descriptionPlaceholder: '请详细描述问题情况',
      titlePlaceholder: '请输入问题标题',
      urgent: '紧急',
      noIssues: '暂无问题记录',
      noIssuesHint: '巡检执行发现异常时将自动生成问题记录',
    },

    // 问题详情
    issueDetail: {
      backToList: '返回列表',
      issueInfo: '问题信息',
      timeline: '处理时间线',
      assignHandler: '指派处理人',
      startProcessing: '开始处理',
      submitResult: '提交处理结果',
      reviewResult: '审核结果',
      closeIssue: '关闭问题',
      selectHandler: '请选择处理人',
      assignSuccess: '处理人已指派',
      startSuccess: '已开始处理',
      resultPlaceholder: '请描述处理结果',
      submitResultSuccess: '处理结果已提交',
      reviewApprove: '审核通过',
      reviewReject: '审核驳回',
      rejectReason: '驳回原因',
      rejectReasonPlaceholder: '请填写驳回原因',
      reviewSuccess: '审核已完成',
      closeConfirm: '确定关闭此问题？',
      closeSuccess: '问题已关闭',
    },

    // 问题上报抽屉
    issueReport: {
      title: '上报问题',
      selectSeverity: '选择严重程度',
      relatedCheckItem: '关联检查项',
      relatedTask: '关联任务',
      submitSuccess: '问题上报成功',
    },

    // 巡检日志
    log: {
      executor: '执行人',
      taskNo: '关联任务',
      checkItem: '检查项',
      executedAt: '执行时间',
      result: '检查结果',
      remark: '备注',
      photos: '现场照片',
      noLogs: '暂无巡检执行记录',
      noLogsHint: '完成巡检任务后，日志将自动生成',
    },

    // 日志详情
    logDetail: {
      backToList: '返回列表',
      logInfo: '日志详情',
      noPhotos: '暂无现场照片',
    },

    // 统计报表
    analytics: {
      dailyTab: '巡检日报',
      stationTab: '站点报表',
      statisticsTab: '安检统计',
      reportsTab: '检查报表',

      // 日报
      dailyDate: '选择日期',
      plannedTasks: '计划任务数',
      completedTasks: '完成任务数',
      completionRate: '完成率',
      abnormalItems: '异常项数',
      executorDetail: '执行人明细',
      abnormalDetail: '异常明细',
      assignedTasks: '分配任务',
      normalItems: '正常项',

      // 站点报表
      timeRange: '时间范围',
      today: '今日',
      thisWeek: '本周',
      thisMonth: '本月',
      custom: '自定义',
      stationName: '站点名称',
      totalTasks: '总任务数',
      abnormalCount: '异常数',
      issueCount: '问题数',
      rectificationRate: '整改率',

      // 安检统计
      overallCompletionRate: '总体完成率',
      overallAbnormalRate: '总体异常率',
      pendingIssueCount: '待处理问题',
      monthlyInspectionCount: '本月巡检次数',
      byTime: '按时间',
      byStation: '按站点',
      byCheckItem: '按检查项目',

      // 检查报表
      reportType: {
        completion: '完成率报表',
        abnormal: '异常分析报表',
        rectification: '整改跟踪报表',
        compliance: '合规报表',
      },
      generateReport: '生成报表',
      generateSuccess: '报表生成成功',
      reportHistory: '历史报表',
      viewReport: '查看报表',
      generatedAt: '生成时间',
      generatedBy: '生成人',
    },

    // 报表详情
    reportDetail: {
      backToAnalytics: '返回统计报表',
      reportInfo: '报表信息',
      exportReport: '导出报表',
      reportContent: '报表内容',
    },
  },

  // 价格管理模块
  price: {
    overview: {
      title: '价格总览',
      fuelTypes: '在售油品',
      overrides: '独立定价枪',
      pending: '待生效调价',
      board: '价格公示',
      viewBoard: '查看看板',
      pendingSchedule: '待生效调价计划',
      detail: '油品价格明细',
    },
    history: {
      title: '调价历史',
      searchPlaceholder: '搜索调价单号/油品/原因',
      detailTitle: '调价详情',
      affectedNozzles: '受影响的枪',
    },
    board: {
      title: '价格公示看板',
      lastUpdate: '最后更新',
      subtitle: '实时价格公示',
      standardPrice: '标准价',
      memberPrice: '会员价',
      maxDiscount: '最高优惠',
      unit: '元',
    },
    approval: {
      title: '调价审批',
      approveTitle: '确认通过调价',
      rejectTitle: '驳回调价',
      approved: '已通过',
      rejected: '已驳回',
      rejectNoteRequired: '驳回必须填写原因',
      rejectNotePlaceholder: '请输入驳回原因（必填）',
      approveNotePlaceholder: '可选备注',
      empty: '暂无待审批的调价申请',
    },
    member: {
      title: '会员专享价',
      add: '新增规则',
      empty: '暂无会员专享价规则',
    },
    agreement: {
      title: '价格协议',
      add: '新增协议',
      enterprise: '企业名称',
      agreedPrice: '协议价',
      discount: '优惠幅度',
      period: '有效期',
      detailTitle: '协议详情',
      searchPlaceholder: '搜索企业名称/油品',
      terminationReason: '终止原因',
      empty: '暂无价格协议',
      expiringSoon: '即将到期',
    },
    settings: {
      title: '价格设置',
      scope: '适用范围',
      global: '全局默认',
      globalConfig: '全局防御配置',
      customConfigs: '站点/品类级配置',
      maxIncrease: '最大涨幅',
      maxDecrease: '最大降幅',
      requireApproval: '需审批',
      approvalThreshold: '审批阈值',
      addConfig: '新增配置',
      empty: '暂无自定义配置',
    },
    field: {
      adjustmentNo: '调价单号',
      fuelType: '油品',
      fuelTypeName: '油品名称',
      basePrice: '基准价',
      currentPrice: '当前价格',
      newPrice: '新价格',
      oldPrice: '原价',
      priceChange: '价格变动',
      change: '变动',
      adjustmentType: '调价类型',
      status: '状态',
      nozzleNo: '枪号',
      nozzleCount: '枪数',
      pricingStatus: '定价状态',
      diff: '与基准差异',
      effectiveAt: '生效时间',
      effectiveFrom: '生效时间',
      lastAdjusted: '最后调价',
      adjustedBy: '发起人',
      approvedBy: '审批人',
      approvedAt: '审批时间',
      approvalNote: '审批备注',
      executedAt: '执行时间',
      createdAt: '创建时间',
      createdBy: '创建人',
      updatedBy: '更新人',
      updatedAt: '更新时间',
      reason: '调价原因',
      memberTier: '会员等级',
      memberPrice: '会员价',
      discountType: '优惠类型',
      discountValue: '优惠值',
      beforePrice: '调价前',
      afterPrice: '调价后',
    },
    action: {
      adjust: '调价',
      nozzleAdjust: '单独调价',
      restoreBase: '恢复基准价',
      restored: '已恢复基准价',
      approve: '通过',
      reject: '驳回',
    },
    confirm: {
      restoreTitle: '确认恢复基准价？',
      restoreDesc: '枪号',
      restoreTo: '将恢复为基准价',
    },
    label: {
      override: '独立',
      overridePrice: '独立定价',
      followBase: '跟随基准',
    },
    filter: {
      allStatus: '全部状态',
      allTypes: '全部类型',
      allFuelTypes: '全部油品',
      allTiers: '全部等级',
    },
    status: {
      pendingApproval: '待审批',
      approved: '待执行',
      rejected: '已驳回',
      executed: '已执行',
      cancelled: '已取消',
    },
    type: {
      immediate: '立即生效',
      scheduled: '定时生效',
    },
    tier: {
      normal: '普通会员',
    },
    agreementStatus: {
      active: '生效中',
      expired: '已过期',
      terminated: '已终止',
    },
    unit: {
      types: '种',
      nozzles: '把',
      items: '条',
      yuan: '元',
    },
    empty: '暂无油品价格数据',
  },

  // 订单与交易模块
  order: {
    list: '订单列表',
    exceptions: '异常订单',
    refunds: '退款管理',
    settings: '订单设置',
    stats: {
      totalOrders: '总订单数',
      totalAmount: '总金额',
      totalQuantity: '总充装量',
      pendingPayment: '待支付',
    },
    action: {
      createOrder: '创建订单',
      export: '导出',
    },
  },
};
