// 中文翻译
export default {
  // 应用
  app: {
    title: '加气站管理系统',
  },

  // 通用
  common: {
    save: '保存',
    cancel: '取消',
    confirm: '确认',
    delete: '删除',
    edit: '编辑',
    add: '新增',
    search: '搜索',
    reset: '重置',
    actions: '操作',
    status: '状态',
    loading: '加载中...',
    noData: '暂无数据',
    success: '操作成功',
    error: '操作失败',
    required: '必填',
    optional: '选填',
    all: '全部',
    enabled: '启用',
    disabled: '停用',
    yes: '是',
    no: '否',
    back: '返回',
    detail: '详情',
    export: '导出',
    import: '导入',
    pageNotFound: '抱歉，您访问的页面不存在',
    backToHome: '返回首页',
    resetFilters: '重置筛选',
    stationUpdateSuccess: '站点更新成功',
    stationCreateSuccess: '站点创建成功',
    submitFailed: '提交失败，请检查表单',
    stationDisabled: '站点已停用',
    viewSwitch: '视图切换',
    tableView: '表格视图',
    cardView: '卡片视图',
    prevStep: '上一步',
    nextStep: '下一步',
    totalRecords: '共 {{total}} 条记录',
    refresh: '刷新',
    autoRefresh: '自动刷新',
  },

  // 导航菜单
  menu: {
    operations: '基础运营',
    station: '站点管理',
    shift: '交接班',
    shiftOverview: '站点概况',
    shiftSchedule: '排班表',
    shiftHistory: '交接历史',
    shiftSettlementReview: '解缴审核',
    equipment: '设备管理',
    inspection: '巡检管理',
  },

  // 用户身份
  user: {
    signOut: '退出登录',
    signOutConfirm: '确定要退出登录吗？',
    signedOut: '已退出登录',
    role: {
      station_master: '站长',
      shift_leader: '班长',
      cashier: '收银员',
      finance: '财务',
    },
  },

  // 站点管理模块
  station: {
    title: '站点管理',
    list: '站点列表',
    detail: '站点详情',
    add: '新增站点',
    edit: '编辑站点',
    
    // 字段
    name: '站点名称',
    code: '站点编码',
    address: '地址',
    longitude: '经度',
    latitude: '纬度',
    contact: '联系人',
    phone: '联系电话',
    businessHours: '营业时间',
    regionLabel: '所属区域',
    groupLabel: '所属分组',
    status: '站点状态',
    
    // 状态
    statusActive: '运营中',
    statusInactive: '已停用',
    statusMaintenance: '维护中',
    
    // 操作
    switchStation: '切换站点',
    selectStation: '请选择站点',
    
    // Tabs
    tabBasic: '基本信息',
    tabNozzle: '枪配置',
    tabShift: '班次排班',
    tabPhoto: '站点照片',
    tabEmployee: '员工管理',
    
    // 枪配置
    nozzle: {
      title: '枪配置',
      list: '枪列表',
      add: '新增枪',
      edit: '编辑枪',
      code: '枪号',
      fuelType: '燃料类型',
      unitPrice: '单价',
      status: '状态',
      setPrice: '设置单价',
      enable: '启用',
      disable: '停用',
      statusOnline: '在线',
      statusOffline: '离线',
      statusFueling: '充装中',
      statusFault: '故障',
      statusIdle: '空闲',
      businessStatus: '业务状态',
      dispenser: '加注岛',
    },
    
    // 设备状态
    device: {
      online: '在线',
      offline: '离线',
      error: '故障',
    },
    
    // 员工
    employee: {
      no: '工号',
      name: '姓名',
      phone: '电话',
      position: '岗位',
      source: '来源',
      sourceSync: '系统同步',
      sourceLocal: '本地维护',
      syncModeSync: '从用户模块同步',
      syncModeLocal: '本地独立维护',
      list: '员工列表',
    },
    
    // 表单
    form: {
      basicInfo: '基础信息',
      locationInfo: '位置信息',
      contactAndBusiness: '联系与营业',
      confirmSubmit: '确认提交',
      stationCodeDesc: '站点名称与编码',
      addressAndRegion: '地址与区域',
      contactAndHours: '联系方式与营业时间',
      infoPreview: '信息预览',
      codeModeAuto: '自动生成',
      codeModeManual: '手工输入',
      autoGenerated: '自动生成',
      weekdayHours: '工作日营业时间',
      weekendHours: '周末营业时间',
      employeeSyncMode: '员工管理模式',
      confirmInfo: '确认信息',
      coordinate: '坐标',
      confirmLeave: '确定要离开吗？未保存的数据将丢失',
      nextStep: '下一步',
    },
    
    // 详情页
    detailPage: {
      stationInfo: '站点信息',
      overview: '统计概览',
      overnight: '跨天',
      nozzleConfig: '枪配置列表',
      refreshStatus: '刷新状态',
      viewNozzleConfig: '查看枪配置',
      errorNozzleAlert: '该站点有 {{count}} 台枪处于故障状态',
      confirmDisableStation: '确定要停用该站点吗？',
      noPhoto: '暂无照片',
    },
  },

  // 燃料类型
  fuelType: {
    gasoline92: '92#汽油',
    gasoline95: '95#汽油',
    gasoline98: '98#汽油',
    diesel: '柴油',
    cng: 'CNG',
    lng: 'LNG',
    other: '其他',
  },

  // 交接班管理模块
  shiftHandover: {
    // 页面标题
    title: '交接班管理',
    summaryTitle: '当班概况',
    historyTitle: '交接历史',
    detailTitle: '交接详情',
    wizardTitle: '交接班流程',
    wizardSubtitle: '请按步骤完成交接班操作',
    settlementReviewTitle: '解缴审核',
    
    // 当班概况
    currentShift: '当前班次',
    shiftTime: '班次时间',
    shiftDuration: '已运营',
    hoursUnit: '小时',
    startHandover: '发起交接',
    viewHistory: '查看历史',
    cashSettlement: '现金解缴',
    settlementReview: '解缴审核',
    
    // 统计数据
    totalAmount: '销售总额',
    totalOrders: '总订单数',
    ordersUnit: '笔',
    netAmount: '净收入',
    abnormalCount: '异常笔数',
    refundCount: '退款笔数',
    refundAmount: '退款金额',
    fuelQuantity: '充装量',
    comparedToPrevious: '较上班次',
    dataRefreshed: '数据已更新',
    refreshFailed: '数据刷新失败，请重试',
    lastUpdated: '最后更新',
    seconds: '秒',
    unsettledCash: '现金待解缴',
    autoRefreshInterval: '自动刷新间隔',
    
    // 金额显示
    hideAmount: '隐藏金额',
    showAmount: '显示金额',
    amountHidden: '****',
    
    // 支付方式
    byPaymentMethod: '按支付方式',
    paymentMethod: '支付方式',
    cash: '现金',
    wechat: '微信支付',
    alipay: '支付宝',
    unionpay: '银联卡',
    prepaid: '预付卡',
    credit: '挂账',
    other: '其他',
    
    // 燃料类型
    byFuelType: '按燃料类型',
    fuelType: '燃料类型',
    quantity: '数量',
    amount: '金额',
    orders: '订单数',
    
    // 交接历史
    dateRange: '日期范围',
    station: '站点',
    shiftName: '班次',
    stationName: '站点名称',
    shiftDate: '班次日期',
    handoverTime: '交接时间',
    handoverBy: '交接人',
    receivedBy: '接班人',
    recordsUnit: '条',
    viewDetail: '查看详情',
    
    // 状态
    initiated: '已发起',
    pendingReview: '待审核',
    completed: '已完成',
    cancelled: '已取消',
    approved: '已通过',
    rejected: '已驳回',
    
    // 详情页
    recordNotFound: '未找到交接记录',
    basicInfo: '基本信息',
    handoverNo: '交接单号',
    salesSummary: '销售汇总',
    issueRecords: '异常记录',
    noIssues: '无异常记录',
    forcedHandover: '强制交接',
    print: '打印',
    remarks: '交接备注',
    
    // 异常
    issueType: '异常类型',
    severity: '严重程度',
    description: '描述',
    reportedBy: '上报人',
    resolved: '已解决',
    unresolved: '未解决',
    
    // 现金解缴
    expectedAmount: '应缴金额',
    actualAmount: '实缴金额',
    difference: '差额',
    differenceReason: '差额原因',
    differenceNote: '差额说明',
    settlementMethod: '解缴方式',
    settlementNo: '解缴单号',
    settlementTime: '解缴时间',
    settlementStatus: '解缴状态',
    submittedBy: '提交人',
    reviewedBy: '审核人',
    reviewedAt: '审核时间',
    
    // 差额类型
    balanced: '无差额',
    overage: '长款 ¥{{amount}}',
    shortage: '短款 ¥{{amount}}',
    
    // 解缴方式
    methodCashBox: '投入钱箱',
    methodSafe: '存入保险柜',
    methodBank: '银行存款',
    
    // 向导步骤
    stepPrecheck: '交接预检',
    stepSummary: '销售汇总',
    stepSettlement: '现金解缴',
    stepConfirm: '确认提交',
    
    // 预检
    precheckTip: '请确认以下事项已完成，带 * 的为必选项',
    checkAll: '全部勾选',
    completeRequiredItems: '请完成所有必选项',
    
    // 解缴
    settlementTip: '请核对并输入实际缴纳的现金金额',
    enterActualAmount: '请输入实缴金额',
    enterDifferenceReason: '差额超过10元，请填写原因',
    differenceReasonPlaceholder: '请说明差额产生的原因',
    
    // 确认
    confirmTip: '请确认以下交接信息无误后提交',
    shiftInfo: '班次信息',
    remarksPlaceholder: '如有需要交接的事项，请在此备注',
    
    // 提交
    confirmSubmit: '确认提交',
    submitSuccess: '交接班提交成功',
    submitFailed: '提交失败，请重试',
    cancelHandover: '取消交接',
    confirmCancel: '确定取消交接吗？',
    cancelWarning: '取消后已填写的数据将丢失',
    
    // 强制交接
    forceHandover: '强制交接',
    forceHandoverTitle: '强制交接确认',
    forceHandoverWarning: '预检项目未全部完成，确定要强制提交交接吗？此操作将被记录。',
    confirmForce: '确认强制提交',
    
    // 完成
    handoverSuccess: '交接班已完成',
    handoverSuccessTip: '交接信息已提交，等待接班人确认',
    backToSummary: '返回当班概况',
    
    // 审核
    review: '审核',
    reviewSettlement: '审核解缴',
    reviewResult: '审核结果',
    approve: '通过',
    reject: '驳回',
    reviewNote: '审核备注',
    reviewNotePlaceholder: '可选填审核备注',
    enterRejectReason: '请填写驳回原因',
    rejectReasonPlaceholder: '请说明驳回原因',
    submitReview: '提交审核',
    reviewApproveSuccess: '审核通过',
    reviewRejectSuccess: '审核已驳回',
    
    // 统计
    pendingReviewCount: '待审核',
    totalDifferenceSum: '差额合计',

    // 接班人选择
    selectReceiver: '选择接班人',
    selectReceiverPlaceholder: '请选择接班人',
    receiverHint: '仅显示当前站点排班表中的人员。如未找到对应人员，请前往「站点管理 → 员工管理」确认该员工已添加至排班表。',
    receiverRequired: '请选择接班人',

    // 排班表
    scheduleTitle: '排班表',
    scheduleThisWeek: '本周',
    scheduleThisMonth: '本月',
    schedulePrevWeek: '上一周',
    scheduleNextWeek: '下一周',
    scheduleAddShift: '新增排班',
    scheduleEditShift: '编辑排班',
    scheduleDate: '日期',
    scheduleShift: '班次',
    scheduleEmployee: '值班人员',
    scheduleSave: '保存',
    scheduleSaveSuccess: '排班保存成功',
    scheduleNoData: '暂无排班数据，请先创建排班',
    scheduleGoToSchedule: '前往创建排班',

    // 站点概况
    overviewTitle: '站点概况',
    currentShiftInfo: '当前班次',
    nextShiftInfo: '下一班次',
    selectStation: '请选择站点',
    switchStation: '切换站点',
    noScheduleHint: '暂无排班信息，请先创建排班',
    scheduled: '已排班',
  },

  // 设备设施管理模块
  deviceLedger: {
    // 设施监控
    monitoring: {
      title: '设施监控',
      totalDevices: '设备总数',
      onlineRate: '在线率',
      alarms: '告警数',
      pendingMaintenance: '待维保',
      tankSection: '储罐状态',
      dispenserSection: '加气机状态',
      pendingActions: '待处理事项',
      autoRefresh: '自动刷新中',
      tankDetail: '储罐监控',
      dispenserDetail: '加气机状态板',
      level: '液位',
      pressure: '压力',
      temperature: '温度',
      trend: '趋势图',
    },
    // 设备台账
    equipment: {
      title: '设备台账',
      add: '新增设备',
      edit: '编辑设备',
      create: '新增设备',
      detail: '设备详情',
      deviceCode: '设备编号',
      name: '名称',
      type: '类型',
      model: '型号',
      status: '状态',
      installDate: '安装日期',
      nextMaintenance: '下次维保',
    },
    // 维保工单
    maintenance: {
      title: '维保工单',
      report: '故障报修',
      createOrder: '创建维保工单',
      submit: '提交工单',
      orderNumber: '工单号',
      type: '类型',
      device: '关联设备',
      urgency: '紧急程度',
      status: '状态',
      assignee: '处理人',
      createdAt: '创建时间',
      description: '描述',
    },
    // 设备连接
    connectivity: {
      title: '设备连接',
    },
  },
};
