// English translations
export default {
  // App
  app: {
    title: 'Gas Station Management',
  },

  // Common
  common: {
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    reset: 'Reset',
    actions: 'Actions',
    status: 'Status',
    loading: 'Loading...',
    noData: 'No Data',
    success: 'Success',
    error: 'Failed',
    required: 'Required',
    optional: 'Optional',
    all: 'All',
    enabled: 'Enabled',
    disabled: 'Disabled',
    yes: 'Yes',
    no: 'No',
    back: 'Back',
    detail: 'Detail',
    export: 'Export',
    import: 'Import',
    pageNotFound: 'Sorry, the page you visited does not exist',
    backToHome: 'Back to Home',
    resetFilters: 'Reset Filters',
    stationUpdateSuccess: 'Station updated successfully',
    stationCreateSuccess: 'Station created successfully',
    submitFailed: 'Submit failed, please check the form',
    stationDisabled: 'Station has been disabled',
    viewSwitch: 'View Switch',
    tableView: 'Table View',
    cardView: 'Card View',
    prevStep: 'Previous',
    nextStep: 'Next',
    totalRecords: 'Total {{total}} records',
    refresh: 'Refresh',
    autoRefresh: 'Auto Refresh',
  },

  // Navigation menu
  menu: {
    operations: 'Operations',
    station: 'Station',
    shift: 'Shift',
    shiftOverview: 'Station Overview',
    shiftSchedule: 'Schedule',
    shiftHistory: 'History',
    shiftSettlementReview: 'Settlement Review',
    equipment: 'Equipment',
    inspection: 'Inspection',
  },

  // User identity
  user: {
    signOut: 'Sign Out',
    signOutConfirm: 'Are you sure to sign out?',
    signedOut: 'Signed out',
    role: {
      station_master: 'Station Master',
      shift_leader: 'Shift Leader',
      cashier: 'Cashier',
      finance: 'Finance',
    },
  },

  // Station management module
  station: {
    title: 'Station Management',
    list: 'Station List',
    detail: 'Station Detail',
    add: 'Add Station',
    edit: 'Edit Station',
    
    // Fields
    name: 'Station Name',
    code: 'Station Code',
    address: 'Address',
    longitude: 'Longitude',
    latitude: 'Latitude',
    contact: 'Contact',
    phone: 'Phone',
    businessHours: 'Business Hours',
    regionLabel: 'Region',
    groupLabel: 'Group',
    status: 'Status',
    
    // Status
    statusActive: 'Active',
    statusInactive: 'Inactive',
    statusMaintenance: 'Maintenance',
    
    // Actions
    switchStation: 'Switch Station',
    selectStation: 'Select Station',
    
    // Tabs
    tabBasic: 'Basic Info',
    tabNozzle: 'Nozzle Config',
    tabShift: 'Shift & Schedule',
    tabPhoto: 'Photos',
    tabEmployee: 'Employees',
    
    // Nozzle configuration
    nozzle: {
      title: 'Nozzle Configuration',
      list: 'Nozzle List',
      add: 'Add Nozzle',
      edit: 'Edit Nozzle',
      code: 'Nozzle Code',
      fuelType: 'Fuel Type',
      unitPrice: 'Unit Price',
      status: 'Status',
      setPrice: 'Set Price',
      enable: 'Enable',
      disable: 'Disable',
      statusOnline: 'Online',
      statusOffline: 'Offline',
      statusFueling: 'Fueling',
      statusFault: 'Fault',
      statusIdle: 'Idle',
      businessStatus: 'Business Status',
      dispenser: 'Dispenser',
    },
    
    // Device status
    device: {
      online: 'Online',
      offline: 'Offline',
      error: 'Fault',
    },
    
    // Employee
    employee: {
      no: 'Employee No',
      name: 'Name',
      phone: 'Phone',
      position: 'Position',
      source: 'Source',
      sourceSync: 'System Sync',
      sourceLocal: 'Local',
      syncModeSync: 'Sync from User Module',
      syncModeLocal: 'Local Maintenance',
      list: 'Employee List',
    },
    
    // Form
    form: {
      basicInfo: 'Basic Info',
      locationInfo: 'Location Info',
      contactAndBusiness: 'Contact & Business',
      confirmSubmit: 'Confirm Submit',
      stationCodeDesc: 'Station Name & Code',
      addressAndRegion: 'Address & Region',
      contactAndHours: 'Contact & Hours',
      infoPreview: 'Info Preview',
      codeModeAuto: 'Auto Generate',
      codeModeManual: 'Manual Input',
      autoGenerated: 'Auto Generated',
      weekdayHours: 'Weekday Hours',
      weekendHours: 'Weekend Hours',
      employeeSyncMode: 'Employee Sync Mode',
      confirmInfo: 'Confirm Info',
      coordinate: 'Coordinate',
      confirmLeave: 'Are you sure to leave? Unsaved data will be lost',
      nextStep: 'Next',
    },
    
    // Detail page
    detailPage: {
      stationInfo: 'Station Info',
      overview: 'Statistics Overview',
      overnight: 'Overnight',
      nozzleConfig: 'Nozzle Config List',
      refreshStatus: 'Refresh Status',
      viewNozzleConfig: 'View Nozzle Config',
      errorNozzleAlert: 'This station has {{count}} nozzle(s) in fault status',
      confirmDisableStation: 'Are you sure to disable this station?',
      noPhoto: 'No Photos',
    },
  },

  // Fuel types
  fuelType: {
    gasoline92: '92# Gasoline',
    gasoline95: '95# Gasoline',
    gasoline98: '98# Gasoline',
    diesel: 'Diesel',
    cng: 'CNG',
    lng: 'LNG',
    other: 'Other',
  },

  // Shift Handover module
  shiftHandover: {
    // Page titles
    title: 'Shift Handover',
    summaryTitle: 'Shift Summary',
    historyTitle: 'Handover History',
    detailTitle: 'Handover Detail',
    wizardTitle: 'Handover Wizard',
    wizardSubtitle: 'Please complete the handover process step by step',
    settlementReviewTitle: 'Settlement Review',
    
    // Current shift
    currentShift: 'Current Shift',
    shiftTime: 'Shift Time',
    shiftDuration: 'Running',
    hoursUnit: 'hours',
    startHandover: 'Start Handover',
    viewHistory: 'View History',
    cashSettlement: 'Cash Settlement',
    settlementReview: 'Settlement Review',
    
    // Statistics
    totalAmount: 'Total Sales',
    totalOrders: 'Total Orders',
    ordersUnit: '',
    netAmount: 'Net Income',
    abnormalCount: 'Abnormal Count',
    refundCount: 'Refund Count',
    refundAmount: 'Refund Amount',
    fuelQuantity: 'Fuel Quantity',
    comparedToPrevious: 'vs Previous Shift',
    dataRefreshed: 'Data updated',
    refreshFailed: 'Refresh failed, please retry',
    lastUpdated: 'Last updated',
    seconds: 's',
    unsettledCash: 'Unsettled Cash',
    autoRefreshInterval: 'Auto Refresh Interval',
    
    // Amount display
    hideAmount: 'Hide Amount',
    showAmount: 'Show Amount',
    amountHidden: '****',
    
    // Payment methods
    byPaymentMethod: 'By Payment Method',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    wechat: 'WeChat Pay',
    alipay: 'Alipay',
    unionpay: 'UnionPay',
    prepaid: 'Prepaid Card',
    credit: 'Credit',
    other: 'Other',
    
    // Fuel types
    byFuelType: 'By Fuel Type',
    fuelType: 'Fuel Type',
    quantity: 'Quantity',
    amount: 'Amount',
    orders: 'Orders',
    
    // Handover history
    dateRange: 'Date Range',
    station: 'Station',
    shiftName: 'Shift',
    stationName: 'Station Name',
    shiftDate: 'Shift Date',
    handoverTime: 'Handover Time',
    handoverBy: 'Handover By',
    receivedBy: 'Received By',
    recordsUnit: '',
    viewDetail: 'View Detail',
    
    // Status
    initiated: 'Initiated',
    pendingReview: 'Pending Review',
    completed: 'Completed',
    cancelled: 'Cancelled',
    approved: 'Approved',
    rejected: 'Rejected',
    
    // Detail page
    recordNotFound: 'Record not found',
    basicInfo: 'Basic Info',
    handoverNo: 'Handover No.',
    salesSummary: 'Sales Summary',
    issueRecords: 'Issue Records',
    noIssues: 'No issues recorded',
    forcedHandover: 'Forced Handover',
    print: 'Print',
    remarks: 'Remarks',
    
    // Issues
    issueType: 'Issue Type',
    severity: 'Severity',
    description: 'Description',
    reportedBy: 'Reported By',
    resolved: 'Resolved',
    unresolved: 'Unresolved',
    
    // Cash settlement
    expectedAmount: 'Expected Amount',
    actualAmount: 'Actual Amount',
    difference: 'Difference',
    differenceReason: 'Difference Reason',
    differenceNote: 'Difference Note',
    settlementMethod: 'Settlement Method',
    settlementNo: 'Settlement No.',
    settlementTime: 'Settlement Time',
    settlementStatus: 'Settlement Status',
    submittedBy: 'Submitted By',
    reviewedBy: 'Reviewed By',
    reviewedAt: 'Reviewed At',
    
    // Difference types
    balanced: 'Balanced',
    overage: 'Over ¥{{amount}}',
    shortage: 'Short ¥{{amount}}',
    
    // Settlement methods
    methodCashBox: 'Cash Box',
    methodSafe: 'Safe',
    methodBank: 'Bank Deposit',
    
    // Wizard steps
    stepPrecheck: 'Pre-check',
    stepSummary: 'Summary',
    stepSettlement: 'Settlement',
    stepConfirm: 'Confirm',
    
    // Pre-check
    precheckTip: 'Please confirm the following items. Items marked with * are required.',
    checkAll: 'Check All',
    completeRequiredItems: 'Please complete all required items',
    
    // Settlement
    settlementTip: 'Please verify and enter the actual cash amount',
    enterActualAmount: 'Please enter actual amount',
    enterDifferenceReason: 'Difference exceeds 10, please explain',
    differenceReasonPlaceholder: 'Please explain the reason for difference',
    
    // Confirm
    confirmTip: 'Please confirm the handover information before submitting',
    shiftInfo: 'Shift Info',
    remarksPlaceholder: 'Enter any notes for the next shift',
    
    // Submit
    confirmSubmit: 'Confirm Submit',
    submitSuccess: 'Handover submitted successfully',
    submitFailed: 'Submit failed, please retry',
    cancelHandover: 'Cancel Handover',
    confirmCancel: 'Cancel handover?',
    cancelWarning: 'Data entered will be lost if you cancel',
    
    // Force handover
    forceHandover: 'Force Handover',
    forceHandoverTitle: 'Force Handover Confirmation',
    forceHandoverWarning: 'Pre-check items are not completed. Are you sure to force submit? This action will be logged.',
    confirmForce: 'Confirm Force Submit',
    
    // Complete
    handoverSuccess: 'Handover Completed',
    handoverSuccessTip: 'Handover has been submitted, waiting for confirmation',
    backToSummary: 'Back to Summary',
    
    // Review
    review: 'Review',
    reviewSettlement: 'Review Settlement',
    reviewResult: 'Review Result',
    approve: 'Approve',
    reject: 'Reject',
    reviewNote: 'Review Note',
    reviewNotePlaceholder: 'Optional review notes',
    enterRejectReason: 'Please enter rejection reason',
    rejectReasonPlaceholder: 'Please explain the rejection reason',
    submitReview: 'Submit Review',
    reviewApproveSuccess: 'Approved',
    reviewRejectSuccess: 'Rejected',
    
    // Statistics
    pendingReviewCount: 'Pending Review',
    totalDifferenceSum: 'Total Difference',

    // Receiver selection
    selectReceiver: 'Select Receiver',
    selectReceiverPlaceholder: 'Select the person taking over',
    receiverHint: 'Only employees in this station\'s schedule are shown. If you cannot find the person, go to "Station → Employees" to ensure they are added to the schedule.',
    receiverRequired: 'Please select a receiver',

    // Schedule
    scheduleTitle: 'Shift Schedule',
    scheduleThisWeek: 'This Week',
    scheduleThisMonth: 'This Month',
    schedulePrevWeek: 'Previous Week',
    scheduleNextWeek: 'Next Week',
    scheduleAddShift: 'Add Schedule',
    scheduleEditShift: 'Edit Schedule',
    scheduleDate: 'Date',
    scheduleShift: 'Shift',
    scheduleEmployee: 'Employee',
    scheduleSave: 'Save',
    scheduleSaveSuccess: 'Schedule saved successfully',
    scheduleNoData: 'No schedule data. Please create schedules first.',
    scheduleGoToSchedule: 'Go to Schedule',

    // Station overview
    overviewTitle: 'Station Overview',
    currentShiftInfo: 'Current Shift',
    nextShiftInfo: 'Next Shift',
    selectStation: 'Select Station',
    switchStation: 'Switch Station',
    noScheduleHint: 'No schedule info. Please create schedules first.',
    scheduled: 'Scheduled',
  },

  // Device & Facility Management
  deviceLedger: {
    monitoring: {
      title: 'Facility Monitoring',
      totalDevices: 'Total Devices',
      onlineRate: 'Online Rate',
      alarms: 'Alarms',
      pendingMaintenance: 'Pending Maintenance',
      tankSection: 'Tank Status',
      dispenserSection: 'Dispenser Status',
      pendingActions: 'Pending Actions',
      autoRefresh: 'Auto Refreshing',
      tankDetail: 'Tank Monitoring',
      dispenserDetail: 'Dispenser Status Board',
      level: 'Level',
      pressure: 'Pressure',
      temperature: 'Temperature',
      trend: 'Trend Chart',
    },
    equipment: {
      title: 'Equipment Ledger',
      add: 'Add Equipment',
      edit: 'Edit Equipment',
      create: 'Add Equipment',
      detail: 'Equipment Detail',
      deviceCode: 'Device Code',
      name: 'Name',
      type: 'Type',
      model: 'Model',
      status: 'Status',
      installDate: 'Install Date',
      nextMaintenance: 'Next Maintenance',
    },
    maintenance: {
      title: 'Maintenance Orders',
      report: 'Report Fault',
      createOrder: 'Create Maintenance Order',
      submit: 'Submit Order',
      orderNumber: 'Order No.',
      type: 'Type',
      device: 'Device',
      urgency: 'Urgency',
      status: 'Status',
      assignee: 'Assignee',
      createdAt: 'Created At',
      description: 'Description',
    },
    connectivity: {
      title: 'Device Connectivity',
    },
  },
};
