// English translations
export default {
  // Common
  common: {
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    reset: 'Reset',
    actions: 'Actions',
    status: 'Status',
    loading: 'Loading...',
    noData: 'No Data',
    success: 'Success',
    error: 'Failed',
    required: 'Required',
    optional: 'Optional',
    all: 'All',
    enabled: 'Enabled',
    disabled: 'Disabled',
    yes: 'Yes',
    no: 'No',
    back: 'Back',
    detail: 'Detail',
    export: 'Export',
    import: 'Import',
    pageNotFound: 'Sorry, the page you visited does not exist',
    backToHome: 'Back to Home',
    resetFilters: 'Reset Filters',
    stationUpdateSuccess: 'Station updated successfully',
    stationCreateSuccess: 'Station created successfully',
    submitFailed: 'Submit failed, please check the form',
    stationDisabled: 'Station has been disabled',
    viewSwitch: 'View Switch',
    tableView: 'Table View',
    cardView: 'Card View',
  },

  // Navigation menu
  menu: {
    operations: 'Operations',
    station: 'Station',
    shift: 'Shift',
    equipment: 'Equipment',
    inspection: 'Inspection',
  },

  // Station management module
  station: {
    title: 'Station Management',
    list: 'Station List',
    detail: 'Station Detail',
    add: 'Add Station',
    edit: 'Edit Station',
    
    // Fields
    name: 'Station Name',
    code: 'Station Code',
    address: 'Address',
    longitude: 'Longitude',
    latitude: 'Latitude',
    contact: 'Contact',
    phone: 'Phone',
    businessHours: 'Business Hours',
    regionLabel: 'Region',
    groupLabel: 'Group',
    status: 'Status',
    
    // Status
    statusActive: 'Active',
    statusInactive: 'Inactive',
    statusMaintenance: 'Maintenance',
    
    // Actions
    switchStation: 'Switch Station',
    selectStation: 'Select Station',
    
    // Tabs
    tabBasic: 'Basic Info',
    tabNozzle: 'Nozzle Config',
    tabShift: 'Shift & Schedule',
    tabPhoto: 'Photos',
    tabEmployee: 'Employees',
    
    // Nozzle configuration
    nozzle: {
      title: 'Nozzle Configuration',
      list: 'Nozzle List',
      add: 'Add Nozzle',
      edit: 'Edit Nozzle',
      code: 'Nozzle Code',
      fuelType: 'Fuel Type',
      unitPrice: 'Unit Price',
      status: 'Status',
      setPrice: 'Set Price',
      enable: 'Enable',
      disable: 'Disable',
      statusOnline: 'Online',
      statusOffline: 'Offline',
      statusFueling: 'Fueling',
      statusFault: 'Fault',
      statusIdle: 'Idle',
      businessStatus: 'Business Status',
      dispenser: 'Dispenser',
    },
    
    // Device status
    device: {
      online: 'Online',
      offline: 'Offline',
      error: 'Fault',
    },
    
    // Employee
    employee: {
      no: 'Employee No',
      name: 'Name',
      phone: 'Phone',
      position: 'Position',
      source: 'Source',
      sourceSync: 'System Sync',
      sourceLocal: 'Local',
      syncModeSync: 'Sync from User Module',
      syncModeLocal: 'Local Maintenance',
      list: 'Employee List',
    },
    
    // Form
    form: {
      basicInfo: 'Basic Info',
      locationInfo: 'Location Info',
      contactAndBusiness: 'Contact & Business',
      confirmSubmit: 'Confirm Submit',
      stationCodeDesc: 'Station Name & Code',
      addressAndRegion: 'Address & Region',
      contactAndHours: 'Contact & Hours',
      infoPreview: 'Info Preview',
      codeModeAuto: 'Auto Generate',
      codeModeManual: 'Manual Input',
      autoGenerated: 'Auto Generated',
      weekdayHours: 'Weekday Hours',
      weekendHours: 'Weekend Hours',
      employeeSyncMode: 'Employee Sync Mode',
      confirmInfo: 'Confirm Info',
      coordinate: 'Coordinate',
      confirmLeave: 'Are you sure to leave? Unsaved data will be lost',
      nextStep: 'Next',
    },
    
    // Detail page
    detailPage: {
      stationInfo: 'Station Info',
      overview: 'Statistics Overview',
      overnight: 'Overnight',
      nozzleConfig: 'Nozzle Config List',
      refreshStatus: 'Refresh Status',
      viewNozzleConfig: 'View Nozzle Config',
      errorNozzleAlert: 'This station has {{count}} nozzle(s) in fault status',
      confirmDisableStation: 'Are you sure to disable this station?',
      noPhoto: 'No Photos',
    },
  },

  // Fuel types
  fuelType: {
    gasoline92: '92# Gasoline',
    gasoline95: '95# Gasoline',
    gasoline98: '98# Gasoline',
    diesel: 'Diesel',
    cng: 'CNG',
    lng: 'LNG',
    other: 'Other',
  },
};
